FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./ ./

#RUN python manage.py db init
#RUN python manage.py db migrate

ENTRYPOINT [ "python" ]
CMD [ "./main.py" ]